### ISSUE TITLE
Unknown Custom Element

### ISSUE THREAD

**Issue by conormcafee** [maoberlehner/building-a-modal-dialog-with-vue-and-vuex#1]
Hi, thanks for the tutorial on making a reusable modal - its been a great help and learning curve for me just starting out with Vue.

I have come across an issue which I can't seen to get my head round - the modal works perfectly until I navigate away from the page to another (using Vue Router), when I go back to a page with the modal i get the following error in the console and it just loads a blank modal

Unknown custom element: <null> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

If i was to refresh the page it works as expected until I navigate back and fourth again - looking at the Vue DevTools I can see that the AppModal's component state remains at null.

Any ideas?

Thanks,

Conor

**Comment by maoberlehner** [comment]
Hey @conormcafee,

thanks for your nice words, I appreciate it.

You've found an error in my example code. I have to rework my article. In the meantime try to do this:

Move the `<app-modal></app-modal>` part of your page (https://github.com/maoberlehner/building-a-modal-dialog-with-vue-and-vuex/blob/master/src/components/PageHome.vue) into your `App.vue` file.

```html
<template>
  <div id="app">
    <page-home></page-home>
    <app-modal></app-modal>
  </div>
</template>

<script>
import AppModal from './components/AppModal';
import PageHome from './components/PageHome';

export default {
  name: 'app',
  components: {
    AppModal,
    PageHome,
  },
};
</script>
```

This should make it work. If not, I'll update this issue as soon as I've updated the article.

Thank you!

**Comment by conormcafee** [comment]
Working as expected now - thanks for your help @maoberlehner
