### ISSUE TITLE
@keyup.esc="hideModal" not working?

### ISSUE THREAD

**Issue by JelleScheer** [maoberlehner/building-a-modal-dialog-with-vue-and-vuex#2]
First of all - thanks for the awesome tutorial, as a beginner in Vuex it's really helping me out!

An issue I'm encountering: the esc keyup event only seems to be triggered when added to an input field and not when added to a normal div, like you did here:

`  <div class="c-appModal" @keydown.esc="hideModal"> `

This isn't only related to your Modal but seems to be the case for the entirety of Vue. Do you have a way to get this to work :)?

Thanks again!

**Comment by maoberlehner** [comment]
Hey @JelleScheer,

Thank you for finding this bug! I'll think about a solution and I'll update my article and this solution in the next few days.
